### PR TITLE
Updated setup-poetry in ci-docs to v8

### PR DESCRIPTION
**Pull request by ddobie**

### CODE REVIEW

**Comment by ddobie** [comment]
@ajstewart I _think_ this should fix it, but as far as I can tell there's no easy way to actually test it. Any thoughts?

**Comment by ajstewart** [comment]
Notice this message on the action as well:
image

I think all the actions should be updated to address that.

As for testing, perhaps change the workflow to be a temporary run on PR to check that it's working and then change it back before merge? There is act: https://github.com/nektos/act but I often find it more frustrating than helpful.

**Comment by ajstewart** [comment]
@ddobie load of dependency nonsense.

Probably dependabot updated something somewhere that caused some regressions to the docs. Had to downgrade jinja2, and then was getting another error of 

```terminal
ERROR    -  Error building page 'reference/query.md': 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 88, in get_item_url
    url = self._url_map[identifier]
KeyError: 'Exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs/commands/build.py", line 314, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs/commands/build.py", line 220, in _build_page
    output = config['plugins'].run_event(
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 197, in on_post_page
    fixed_output, unmapped = fix_refs(output, url_mapper)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs_autorefs/references.py", line 186, in fix_refs
    html = AUTO_REF_RE.sub(fix_ref(url_mapper, unmapped), html)
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs_autorefs/references.py", line 156, in inner
    url = url_mapper(unescape(identifier))
  File "/usr/local/Caskroom/mambaforge/base/envs/vast-tools/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 95, in get_item_url
    for new_identifier in new_identifiers:
TypeError: 'NoneType' object is not iterable
```

which was solved by updating `mkdocstrings` (https://github.com/mkdocstrings/autorefs/issues/14).

The dependencies and even the poetry toml format needs an overhaul as they are all quite outdated.

**Review by ajstewart — APPROVED** [review]

**Comment by ddobie** [comment]
Legend. Thanks!

**Pull request merged**
