### PR TITLE
Remove epoch 12 user warning

### LINKED ISSUE #360: Remove epoch 12 warning

### PR DESCRIPTION
**Pull request by ddobie**
Fix #360.

### CODE REVIEW

**Comment by ajstewart** [comment]
In the docs there are also prominent warnings like this one: https://www.vast-survey.org/vast-tools/components/query/, and is repeated on other pages.

All the per-page warnings could probably be removed now with perhaps just a warning on the data access page in getting started, would you agree?

**Comment by ddobie** [comment]
Agreed!

**Review by ajstewart — APPROVED** [review]
Is it worth putting a note about it on the data page or just leave it to the changelog?

I was always uneasy at vast tools containing information about the actual data release as that should be its own thing.

But good to go in any case!

**Comment by ddobie** [comment]
> Is it worth putting a note about it on the data page or just leave it to the changelog?
> 
> I was always uneasy at vast tools containing information about the actual data release as that should be its own thing.
> 
> But good to go in any case!

I think it's probably good as-is.

There's a warning in the data access section of the docs that states which version of the data release the package is compatible with (although that's probably outdated now). Maybe it's worth having something more explicit on the introduction page that lists what versions of the data and pipeline the version of tools works with. I'll add that to my to-do list in #352/#354.

**Pull request merged**
