### PR TITLE
Dependency refresh and bumps

### PR DESCRIPTION
**Pull request by ajstewart**
* Limited python version to <3.11.
* poetry update on packages.

Noteable upgrades:
* `astropy` v4.3 -> v5.0.
* `mkdocs-material` v7.3.0 -> v8.2.4.

Fixed minor regressions, deprecations and tests.

To do:
- [ ] Check notebooks.

### CODE REVIEW

**Comment by ajstewart** [comment]
@ddobie I expect you'd only want to merge this after a v3.0 is stable for people to actually use.

But it's here for when that happens and this will also make #330 trivial to implement.

Astropy v5.0 seems to have no major breaking changes and all the tests seem to pass. But the notebooks will definitely need going through beforehand to mimic a complete end-to-end test.

**Comment by ddobie** [comment]
@ajstewart I've tested the notebooks on the jupyterhub in a python 3.9 environment. All run fine.

I've also tested the docs build - there were some major problems stemming from the mkdocs-material bump, but they're now mostly fixed. The only potential problem is that when I run `mkdocs serve` I get a boatload of warnings of the form
```
INFO    -  Doc file 'components/tools.md' contains an unrecognized relative link
           '../../reference/tools/#vasttools.tools.WisePatchConfig', it was left
           as is. Did you mean
           '../reference/tools.md#vasttools.tools.WisePatchConfig'?
```

I've checked the website locally and those links work fine, so it seems to just be a weird check/logging thing. I can't find anything online addressing this, have you run into it before? I think it's fine to ignore it, but it would be good to fix it if there's an easy fix.

**Comment by ajstewart** [comment]
> @ajstewart I've tested the notebooks on the jupyterhub in a python 3.9 environment. All run fine.
> 
> I've also tested the docs build - there were some major problems stemming from the mkdocs-material bump, but they're now mostly fixed. The only potential problem that I've not been able to resolve is that when I run `mkdocs serve` I get a boatload of warnings of the form
> 
> ```
> INFO    -  Doc file 'components/tools.md' contains an unrecognized relative link
>            '../../reference/tools/#vasttools.tools.WisePatchConfig', it was left
>            as is. Did you mean
>            '../reference/tools.md#vasttools.tools.WisePatchConfig'?
> ```
> 
> I've checked the website locally and those links work fine, so it seems to just be a weird check/logging thing. I can't find anything online addressing this, have you run into it before? I think it's fine to ignore it, but it would be good to fix it if there's an easy fix.

If it works then I'd say don't worry about it.

At a guess I imagine it's something to do with `mkdocstrings` which also seems to be using the `python-legacy`, though I don't remember why this was required, though there must be a reason. There is `mkdocstrings[python]` which should do the job and is more up-to-date.

Also - there are a few `^0.X` defined in the poetry dev section that haven't been updated, and won't update to anything meaningful because of that restriction (I say this as `mkdocstrings` is one of them).

Though can't speak on its compatibility with the other plugins in use here (did lightbox break?)

Shame that is seems like `vaex` is the issue for python 3.11? As I would have said getting it working on 3.10+ probably is best now, dropping 3.8 and 3.9.

**Comment by ddobie** [comment]
I've updated more where I can.

Lightgallery doesn't seem to be supported anymore. Removing it hasn't had any severe impact on the docs so I don't think it's an issue.

Looks like there's plans for vaex python 3.11 support, but it's not finished (https://github.com/vaexio/vaex/issues/2368)

I think the best way forward is to make these changes that maintain python 3.8 support, and then in the next month or two make a separate change that bumps to requiring python>3.10 and updates packages that were limited by a lack of python 3.11 support or by no longer supporting python 3.8. I've summarised those planned changes in #559.

**Comment by ddobie** [comment]
@ajstewart I think this is good to go, but I thought I should give you the chance for a final approval since it's your PR!

**Comment by ajstewart** [comment]
> @ajstewart I think this is good to go, but I thought I should give you the chance for a final approval since it's your PR!

Looks good to me! I think you've probably overwritten my changes in any case! Is astropy 6.0 breaking?

Hopefully vaex doesn't hold you back for too long.

**Comment by ddobie** [comment]
Yes, astropy >5.3 requires python >=3.9

**Review by ddobie — APPROVED** [review]

**Pull request merged**
